test_groups:
  - group_id: 1
    boxes:
      - [1.69, 0.219, -0.012]
      - [-0.897, -1.228, -0.183]
      - [0.259, 1.7, 0.072]
  - group_id: 2
    boxes:
      - [-1.906, -1.116, -0.259]
      - [-0.889, -0.906, 0.306]
      - [0.436, -1.273, -0.315]
  - group_id: 3
    boxes:
      - [1.530, -1.733, -0.300]
      - [0.933, -0.998,  0.000]
      - [0.609,  1.677,  0.300]
  - group_id: 4
    boxes:
      - [0.172,  1.602, -0.300]
      - [2.003, -0.990,  0.000]
      - [-0.081,  1.536,  0.300]
