
test_groups:
  - group_id: 1
    boxes:
      - [-0.716,  1.016,  0.154] # r=1.24m, theta=125.2° (Q2)
      - [ 0.567, -1.188,  0.362] # r=1.32m, theta=-64.5° (Q4)
      - [ 1.285, -1.095,  0.069] # r=1.69m, theta=-40.4° (Q4)

  - group_id: 2
    boxes:
      - [ 0.688,  1.422, -0.072] # r=1.58m, theta=64.2°  (Q1)
      - [ 0.750, -1.399,  0.188] # r=1.59m, theta=-61.8° (Q4)
      - [-0.399, -1.896,  0.244] # r=1.94m, theta=-101.9°(Q3)

  - group_id: 3
    boxes:
      - [ 1.403,  0.706,  0.027] # r=1.57m, theta=26.7°  (Q1)
      - [-0.821,  1.430,  0.043] # r=1.65m, theta=119.9° (Q2)
      - [ 1.502, -0.744,  0.089] # r=1.68m, theta=-26.3° (Q4)

  - group_id: 4
    boxes:
      - [ 0.892, -1.040,  0.379] # r=1.37m, theta=-49.4° (Q4)
      - [ 0.399, -1.438,  0.351] # r=1.49m, theta=-74.5° (Q4)
      - [ 0.201,  1.742,  0.086] # r=1.75m, theta=83.4°  (Q1)

  - group_id: 5
    boxes:
      - [ 0.453,  1.140,  0.101] # r=1.23m, theta=68.3°  (Q1)
      - [ 0.474,  1.630,  0.163] # r=1.70m, theta=73.8°  (Q1)
      - [-0.123, -1.853,  0.001] # r=1.86m, theta=-93.8° (Q3)

  - group_id: 6
    boxes:
      - [ 0.414, -1.145,  0.243] # r=1.22m, theta=-70.1° (Q4)
      - [-1.285,  0.846,  0.078] # r=1.54m, theta=146.7° (Q2)
      - [-1.116, -1.550, -0.076] # r=1.91m, theta=-125.8°(Q3)
