test_groups:
  - group_id: 1
    boxes:
      - [1.69, 0.219, -0.012]
      - [-0.897, -1.228, -0.183]
      - [0.259, 1.7, 0.072]
  - group_id: 2
    boxes:
      - [0.562, 1.709, -0.178]
      - [-1.150, 0.981, 0.064]
      - [-0.246, 1.894, 0.150]
  - group_id: 3
    boxes:
      - [0.568, 1.477, 0.051]
      - [-1.863, 0.118, 0.074]
      - [0.913, 1.363, 0.179]
